name: Build Drivers

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    container:
      image: ubuntu:latest # 使用Ubuntu 22.04容器环境

    env:
      KVER : "6.8.0-31-generic"
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: |
        uname -r
        apt-get update
        apt-get install -y build-essential linux-headers-generic
        
    - name: Build project
      run: make KVER=${{env.KVER}}

    - name: Upload release
      uses: actions/upload-artifact@v3
      with:
        name: rtl8723bs
        path: r8723bs.ko
