name: Build Drivers

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:16.04 # 使用Ubuntu 16.04容器环境
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y build-essential linux-headers-4.4.0-98
    - name: Build project
      run: make
