name: Build Drivers

on:
  push:
    branches:
      - test1
  pull_request:
    branches:
      - test1

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:16.04 # 使用Ubuntu 16.04容器环境
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential linux-headers-$(uname -r)
    - name: Build project
      run: make
